### PR TITLE
removed shrinkwrap and update dependency

### PR DESCRIPTION
**Pull request by ftaiolivista**
Fix problem with ansi-style
see https://github.com/npm/npm/issues/17723#issuecomment-314745001

### CODE REVIEW

**Comment by fjorgemota** [comment]
Thanks! :)

**Comment by string01** [comment]
I'm not familiar with this project as it is used by some tools we use that use 'npm install'. 
When will this fix get built and release?
Thanks.

**Comment by fjorgemota** [comment]
@string01 Please see issue #9 =)

Thanks.

**Comment by string01** [comment]
Thank you.

**Pull request merged**
